### ISSUE TITLE
Subcircuit parameters are not evaluated

### ISSUE THREAD

**Issue by OndrejBukovsky** [MatyasVasek/SymCirc#14] opened 2024-10-29 14:03 UTC
**Describe the bug**
Subcircuit parameters (K1 and K2) are not evaluated. Although default values are given. In addition, there is a strange result "v(o2_(X1))".

Output:
```
{'v(1)': x, 'v(2)': y, 'v(sum)': K1*x + K2*y, 'v(o2_(X1))': K2*y}
```

**To Reproduce**
```python
from symcirc import *

netlist = """

V1 1 0 DC x
V2 2 0 DC y
X1 1 2 sum sumator_mod 

.subckt sumator_mod in1 in2 outs PARAMS: K1=1 K2=1
E1sum outs o2 in1 0 K1
E2sum o2 0 in2 0 K2
.ends sumator_mod
"""

circuit = AnalyseCircuit(netlist, "DC", symbolic=False)
results = circuit.node_voltages()

print(results)
```

**Expected behavior**
```
{'v(sum)': x + y, ...}
```

**Additional context**
Maple script for comparison.
```
restart;

with(PraCAn):

_netlist := "

V1 1 0 DC x
V2 2 0 DC y
X1 1 2 sum sumatormod 

.subckt sumatormod in1 in2 outs PARAMS: K1=1 K2=1
E1sum outs o2 in1 0 K1
E2sum o2 0 in2 0 K2
.ends sumatormod
.end":

ParseCircuit(_netlist);

SetAnalysis(dc, numeric, SAVE=all):

_pracanResults:=Analyze()[2]:
subs(_pracanResults,v("sum"));
```

**Comment by MatyasVasek** [comment] 2024-10-30 10:22
Thanks for the bug catch. It was caused by the parser. A fix for this issue will be included in the next version (0.1.3).
In regards to the "strange" result: It's the voltage on an internal subcircuit node. These can be identified by the "_(<subcircuit_name>)" appendage.

**Closed by MatyasVasek** 2024-10-30 10:22 UTC
Labels: bug
